### ISSUE TITLE
Docs: more code ssmples/examples?

### ISSUE THREAD

**Issue by ArulGandhi** [apilol/PyDefender#4]
How do I use this? Gimme a verbose explanation and I'll expand the readme and even create an examples folder. Thanks!

**Comment by faintastic** [comment]
https://github.com/faintastic/PyDefender/blob/dev/examples/defender.py

**Comment by ArulGandhi** [comment]
Seen this. Anything else? More specifically, to turn off real time protection?

**Comment by ArulGandhi** [comment]
Seen this. Anything else? More specifically, to turn off real time protection?

**Comment by faintastic** [comment]
How to turn off real time protection on the users computer? They have to go into windows security.

**Comment by ArulGandhi** [comment]
Is it avoidable? (going into win security)

**Comment by faintastic** [comment]
Disabling it no, but you can make it not get detected by windows security. But I will not provide steps on how to do that.

**Comment by ArulGandhi** [comment]
Fair enough. I'll close this
